### ISSUE TITLE
Updating the UI from a PeriodicTimer

### ISSUE THREAD

**Issue by gtejeda** [phorks/phork-blazor-reactivity#3]
Greetings, I'm modifying the state from a PeriodicTimer in Blazor, specifically from a method in the service class which makes the httpcalls and updates the state (2 observable Collections), however, the UI is not being updated.

My blazor component has the Observer attribute in place

```
[Action]
    async Task HandleTimerAsync(PeriodicTimer timer, CancellationToken cancel = default)
    {
        try
        {
            while (await timer.WaitForNextTickAsync(cancel))
            {
                await synchronizer. Synchronize();
                await InvokeAsync(() => StateHasChanged());
            }
        }
        catch (Exception)
        {
            //Handle the exception but don't propagate it
        }
    }
```

One of the collections I update like this
```
public ObservableCollection<ConversationDTo> Conversations { get; private set; }
        public void AddConversation(ConversationDTo conversation)
        {
            Conversations.Add(conversation);
        }
        public void UpdateConversation(ConversationDTo conversation)
        {
            var oldItem = Conversations.FirstOrDefault(i => i.Id == conversation.Id);
            var oldIndex = Conversations.IndexOf(oldItem);
            Conversations[oldIndex] = conversation;
        }
```

And finally, in the view where I inherit from ReactiveComponentBase, I have the following:
```
@if (synchronizer != null && synchronizer.Conversations != null)
            {
                foreach (var item in ObservedCollection(() => synchronizer.Conversations))
                {
                    <MudText Style="font-weight: bolder">Canal: @item.Channel (@item.Messages.Count mensajes)</MudText>
                    <MudText>@item.Id</MudText>

                    <ul>
                        @foreach(var msg in item.Messages)
                        {
                            <li>@msg.Contents</li>
                        }
                    </ul>
                    <br />
                }
            }
            else
            {
                <MudText>No conversations</MudText>
            }
```

If i manually call refresh, the UI updates with all the data there, so the PeriodicTimer is running... any advice would be appreciated.

Thanks in advance,
Geo

**Comment by phorks** [comment]
Hi Geo,

The only red flag I see in your code is that the `Conversations` property is not read-only. Is there any chance that the `Conversations` object might get changed after the component renders for the first time? If that's the case, the component must be notified when it changes. You should implement `INotifyPropertyChanged` in your `synchronizer` class and raise `PropertyChanged` in the setter of the property (see how the `Person` class implements `INotifyPropertyChanged` [here](https://github.com/phorks/phork-blazor-reactivity/blob/main/docs/IN-ACTION.md)). Then you should check for `Observed(() => synchronizer.Conversations) != null` instead of `synchronizer.Conversations != null`. 

If this is not the case, please provide a minimal reproducible example, so that I can reproduce the problem and try to find out the cause.

**Comment by phorks** [comment]
Closing as no response was received from the OP. Feel free to reopen it if the problem is not resolved.
